# Generated by Django 2.1 on 2018-08-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0002_message_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
    ]
