# Generated by Django 2.1 on 2018-08-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0003_ipname'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
                ('datetime', models.DateTimeField(verbose_name='datetime')),
            ],
        ),
    ]
